# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
linter:
  rules:
    - annotate_overrides
    - await_only_futures
    - directives_ordering
    - public_member_api_docs
    - sort_pub_dependencies
    - unnecessary_parenthesis

analyzer:
#   exclude:
#     - path/to/excluded/files/**
