name: glob_export
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  build: ^1.1.3
  code_builder: ^3.2.0
  dart_style: ^1.2.7
  glob: ^1.1.7
  path: ^1.6.2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
