name: glob_export
description: A builder package for automatically exporting Dart files in a project based on globs.
version: 0.1.2
homepage: https://www.github.com/quantumAssembly/glob_export
author: Kai Page <kaibug@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  build: ^1.1.0
  code_builder: ^3.2.0
  dart_style: ^1.2.0
  glob: ^1.1.0
  path: ^1.6.0

dev_dependencies:
  build_runner: ^1.3.1
  pedantic: ^1.0.0
  test: ^1.0.0
